### ISSUE TITLE
mtl dependency

### ISSUE THREAD

**Issue by paolino** [kaoskorobase/hsc3-process#1]
The 2.0.1.\* mtl dependency is downgrading all others hsc3 packages. Can it be moved to 2.1.2 ?

**Comment by kaoskorobase** [comment]
hey sorry, have seen the issue just now. shouldn't be a problem, will have a look asap.

**Comment by paolino** [comment]
Thanks

paolino

2012/11/1 Stefan Kersten notifications@github.com

**Comment by kaoskorobase** [comment]
Paolino,

HEAD doesn't have a dependency on mtl anymore, I'll make a new release this week. In the meantime you can use the version from git.

**Comment by kaoskorobase** [comment]
Version 0.7.0 is already released on [Hackage](http://hackage.haskell.org/package/hsc3-process)
